[package]
name = "wrapper"
version = "0.1.0"
authors = ["tjan <earltjan@foxmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
libc = "0.2.58" # same with filecoin-project/filecoin-ffi
storage-proofs = "4.0.1"
serde_json = "1.0.57"
rand = "0.7.3"
chrono = "0.4.13"
memmap = "0.7.0"
tempdir = "0.3.7"
anyhow = "1.0.32"
merkletree = "0.21.0"
